### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/Android-Youtube-Video-Player#1]
Update readme to something like https://github.com/arshadkazmi42/android-custom-camera-with-live-filter/blob/master/README.md

**Comment by darkdraiden14** [comment]
I can do this if you like

**Comment by arshadkazmi42** [comment]
@darkdraiden14 Sure go ahead

**Comment by darkdraiden14** [comment]
Done Please have a look
#2
